name: Jekyll site CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

   # build:

   #  runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [10.x, 12.x, 14.x]

    # steps:
    # - uses: actions/checkout@v2
    # - name: Use Node.js ${{ matrix.node-version }}
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node-version }}
    # - name: Install Dependencies
    #   working-directory: ./core-ui
    #   run: npm ci
    # - name: Build Core UI
    #   working-directory: ./core-ui
    #   run: npm run build --if-present

  deploy-core-ui:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install Dependencies
      # working-directory: ./core-main/core-ui/
      run: npm install
  

    - name: Build Core UI
      # working-directory: ./core-main/core-ui
      run: npm run build --if-present
      
      

  # deploy-core-server:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Checkout Repository
  #     uses: actions/checkout@v2

  #   - name: Setup Node.js
  #     uses: actions/setup-node@v2
  #     with:
  #       node-version: 14

  #   - name: Install Dependencies
  #     working-directory: ./core-server #Error: Cannot find module '/home/runner/work/core-main/core-main/core-ui/app.js'
  #     run: npm install

  #   - name: Build Core Server
  #     working-directory: ./core-server
  #     run: node app.js
